Project_Krekelhof/Models/Domain/Boek.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project_Krekelhof.Models.Domain
{
    public class Boek : Item
    {
        public string Auteur { get; set; }
        public string Isbn { get; set; }
        public string Uitgeverij { get; set; }
        public string Leeftijd { get; set; }
        public virtual Categorie Categorie { get; set; }

        public Boek()
        {
            
        }

        public Boek(int id, string naam, string beschrijving, bool beschikbaar, string auteur, string ISBN, string uitgeverij, string leeftijd, Categorie categorie)
            : base(id, naam, beschrijving, beschikbaar)
        {
            this.Auteur = auteur;
            this.Isbn = ISBN;
            this.Uitgeverij = uitgeverij;
            this.Leeftijd = leeftijd;
            this.Categorie = categorie;
        }    
    }
}

Project_Krekelhof/ViewModels/BoekViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project_Krekelhof.Models.Domain;

namespace Project_Krekelhof.ViewModels
{

    public class BoekViewModel
    {
        public int Id { get; set; }
        public string Naam { get; set; }
        public string Omschrijving { get; set; }
        public string Auteur { get; set; }
        public string Uitgeverij { get; set; }
        public string Leeftijd { get; set; }
        public string Isbn { get; set; }
        public int CategroieId { get; set; }
        public string Categorie { get; set; }
        public bool Beschikbaar { get; set; }

        public BoekViewModel()
        {
            
        }

        public BoekViewModel(Boek b)
        {
            Id = b.Id;
            Naam = b.Naam;
            Omschrijving = b.Omschrijving;
            Auteur = b.Auteur;
            Uitgeverij = b.Uitgeverij;
            Leeftijd = b.Leeftijd;
            Isbn = b.Isbn;
            //CategroieId = (b.Categorie == null) ? 0 : b.Categorie.Id;
            Categorie = (b.Categorie == null) ? null : b.Categorie.Naam;
            Beschikbaar = b.Beschikbaar;
        }
    }
    
    public class BoekIndexViewModel
    {      
        public IEnumerable<BoekViewModel> Boeken { get; set; }

        public BoekIndexViewModel(IEnumerable<Boek> boeken)
        {
            Boeken = boeken.Select(b => new BoekViewModel(){
                Id = b.Id,
                Naam = b.Naam,
                Omschrijving = b.Omschrijving,
                Auteur = b.Auteur,
                Uitgeverij = b.Uitgeverij,
                Leeftijd = b.Leeftijd,
                Isbn = b.Isbn,
                Categorie = b.Categorie.Naam,
                Beschikbaar = b.Beschikbaar
            });
        }
    }
}

Project_Krekelhof/Controllers/BoekController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project_Krekelhof.Models.DAL;
using Project_Krekelhof.Models.Domain;
using Project_Krekelhof.ViewModels;

namespace Project_Krekelhof.Controllers
{
    public class BoekController : Controller
    {

        private Gebruiker gebruiker;
        private Medewerker medewerker;

        private IBoekRepository boekRepository;
        private ICategorieRepository categorieRepository;

        private IUitleningRepository uitleningRepository;
        private ILeerlingRepository leerlingRepository;

        public BoekController(IBoekRepository boekRepository, ICategorieRepository categorieRepository, IUitleningRepository uitleningRepository, ILeerlingRepository leerlingRepository)
        {
            gebruiker = new Gebruiker(boekRepository, categorieRepository, null, null, null, null, null);
            medewerker = new Medewerker(boekRepository, categorieRepository, null, null, null, null, null);

            this.boekRepository = boekRepository;
            this.categorieRepository = categorieRepository;
            this.uitleningRepository = uitleningRepository;
            this.leerlingRepository = leerlingRepository;
        }

        public ActionResult Index(String zoekstring)
        {
            IEnumerable<Boek> boeken;
            if (!String.IsNullOrEmpty(zoekstring))
            {
                boeken = gebruiker.GeefBoeken(zoekstring);
                ViewBag.Selection = "Alle boeken met '"  + zoekstring + "'";
            }
            else
            {
                boeken = gebruiker.GeefBoeken(zoekstring);
                ViewBag.Selection = "Alle boeken";
            }
            if (Request.IsAjaxRequest())
                return PartialView("Lijst", new BoekIndexViewModel(boeken));

            return View(new BoekIndexViewModel(boeken));
        }

        [HttpGet]
        public ActionResult Create()
        {
            Boek boek = new Boek();
            ViewBag.Title = "Boek toevoegen";
            ViewBag.Categorie = GetCategorieSelectList(boek);
            return View(new BoekViewModel(boek));
        }

        [HttpPost]
        public ActionResult Create(BoekViewModel bvm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Boek boek = new Boek();
                    MapToBoek(bvm, boek);
                    boekRepository.Add(boek);
                    boekRepository.SaveChanges();
                    TempData["Message"] = String.Format("{0} werd gecreëerd.", boek.Naam);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            ViewBag.Categorie = GetCategorieSelectList(bvm.Categorie);
            return View(bvm);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Boek boek = boekRepository.FindById(id);
            if (boek == null)
                return HttpNotFound();
            ViewBag.Categorie = GetCategorieSelectList(boek);
            return View("Create", new BoekViewModel(boek));
        }

        [HttpPost]
        public ActionResult Edit(int id, BoekViewModel bvm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Boek boek = boekRepository.FindById(id);
                    MapToBoek(bvm, boek);
                    boekRepository.SaveChanges();
                    TempData["message"] = String.Format("Boek {0} werd aangepast", boek.Naam);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            ViewBag.Categorie = GetCategorieSelectList(bvm.Categorie);
            return View("Create", bvm);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Boek boek = boekRepository.FindById(id);
            if (boek == null)
                return HttpNotFound();
            return View(new BoekViewModel(boek));
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Boek boek = boekRepository.FindById(id);
                if (boek == null)
                    return HttpNotFound();
                boekRepository.Remove(boek);
                boekRepository.SaveChanges();
                TempData["message"] = String.Format("Boek {0} werd verwijderd", boek.Naam);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Verwijderen Boek mislukt. Probeer opnieuw. ";
            }
            return RedirectToAction("Index");
        }



        private void MapToBoek(BoekViewModel bvm, Boek boek)
        {
            boek.Id = bvm.Id;
            boek.Naam = bvm.Naam;
            boek.Omschrijving = bvm.Omschrijving;
            boek.Auteur = bvm.Auteur;
            boek.Uitgeverij = bvm.Uitgeverij;
            boek.Isbn = bvm.Isbn;
            boek.Leeftijd = bvm.Leeftijd;
            boek.Categorie = (String.IsNullOrEmpty(bvm.Categorie) ? null : categorieRepository.FindById(Int32.Parse(bvm.Categorie)));
            boek.Beschikbaar = bvm.Beschikbaar;
        }

        private SelectList GetCategorieSelectList(Boek boek)
        {
            return new SelectList(categorieRepository.FindAll().OrderBy(g => g.Naam),
                "Id", "Naam",
               boek == null || boek.Categorie == null ? "" : boek.Categorie.Naam);
        }

        private SelectList GetCategorieSelectList(string categorie)
        {
            return new SelectList(categorieRepository.FindAll().OrderBy(g => g.Naam),
                "Id", "Naam",
               categorie ?? "");
        }


        //public ActionResult Uitlenen()
        //{
        //    IEnumerable<Leerling> Leerlingen;
        //    Leerlingen = leerlingRepository.FindAll();
        //    return PartialView("Uitlenen", new LeerlingIndexViewModel(Leerlingen));
        //    Uitlening uitlening = new Uitlening();
        //    ViewBag.Title = "Boek toevoegen";
        //    ViewBag.Leerling = GetLeerlingSelectList(uitlening);
        //    return PartialView("Uitlenen", new LeerlingIndexViewModel(Leerlingen));
        //}

        //[HttpPost, ActionName("Uitlenen")]
        //public ActionResult UitleningT(UitleningViewModel uvm, int id)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            Boek boek = boekRepository.FindById(id);
        //            Uitlening uitlening = new Uitlening();
        //            MapToUitlening(uvm, uitlening);
        //            uitleningRepository.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        catch (Exception ex)
        //        {
        //            ModelState.AddModelError("", ex.Message);
        //        }
        //    }
        //    ViewBag.Categorie = GetCategorieSelectList(uvm.volledigeNaam);
        //    return PartialView("Uitlenen");
        //}

        //private void MapToUitlening(UitleningViewModel uvm, Uitlening uitlening)
        //{
        //    uitlening.Item.Naam = uvm.Item;
        //    uitlening.Leerling.Voornaam = uvm.volledigeNaam;
        //}

        //private SelectList GetLeerlingSelectList(Uitlening uitlening)
        //{
        //    return new SelectList(categorieRepository.FindAll().OrderBy(g => g.Naam),
        //        "Id", "Naam",
        //       uitlening == null || uitlening.Leerling == null ? "" : uitlening.Leerling.ToString());
        //}

        //private SelectList GetLeerlingSelectList(string leerling)
        //{
        //    return new SelectList(leerlingRepository.FindAll().OrderBy(g => g.ToString()),
        //        "Id", "Naam",
        //       leerling ?? "");
        //}
    }
}

Project_Krekelhof/Views/Boek/BoekenLijst.cshtml
<link href="~/Content/Leerlingen.css" rel="stylesheet" type="text/css" />

@model Project_Krekelhof.ViewModels.BoekIndexViewModel

<div id="modal-container" class="modal fade"
     tabindex="-1" role="dialog">
    <div class="modal-content">
    </div>
</div>
<style>
    .modal-content {
        width: 600px !important;
        margin: 30px auto !important;
    }
</style>



<table class="table" >
    <tr style="text-align:center;">
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Naam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Auteur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Uitgeverij)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Omschrijving)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Leeftijd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Isbn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Beschikbaar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Boeken.FirstOrDefault().Categorie)
        </th>
        <th></th>
    </tr>

 
    @if (Request["beschikbaar"] == "beschikbaar")
    {
        foreach (var item in Model.Boeken)
        {
            if (item.Beschikbaar == true)
            {
                <tr id="tabelrijen">
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Auteur)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Uitgeverij)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Omschrijving)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Leeftijd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Isbn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Beschikbaar)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Categorie)
                    </td>
                    <td>

                        <a>
                            <img src="~/Images/Bewerken.png" style="width:10px; height:10px;" />
                            @Html.ActionLink("Aanpassen", "Edit", new { id = item.Id }) |

                        </a>
                        @Html.ActionLink("Verwijderen", "Delete", new { id = item.Id, @class = "Deleteknop" }) |
                        @Html.ActionLink("Uitlening", "Uitlenen", null, new { @class = "modal-link btn btn-success" })
                    </td>
                </tr>
            }

        }
    }
    else{
        
        foreach (var item in Model.Boeken)
        {
            <tr id="tabelrijen">
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Auteur)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Uitgeverij)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Omschrijving)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Leeftijd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Isbn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Beschikbaar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categorie)
                </td>
                <td>

                    <a>
                        <img src="~/Images/Bewerken.png" style="width:10px; height:10px;" />
                        @Html.ActionLink("Aanpassen", "Edit", new { id = item.Id }) |

                    </a>
                    @Html.ActionLink("Verwijderen", "Delete", new { id = item.Id, @class = "Deleteknop" }) |
                    @Html.ActionLink("Uitlening", "Uitlenen", null, new { @class = "modal-link btn btn-success" })
                </td>
            </tr>
        }
    }


</table>

Project_Krekelhof/Views/Boek/Create.cshtml
@model Project_Krekelhof.ViewModels.BoekViewModel

@{
    if (@Model.Id == 0)
    {
        ViewBag.Title = "Creëer boek";
    }
    else
    {
        ViewBag.Title = "Editeer boek";
    }
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Omschrijving, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Omschrijving, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Omschrijving, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Auteur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Auteur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Auteur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uitgeverij, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uitgeverij, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uitgeverij, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Leeftijd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Leeftijd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Leeftijd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Isbn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Isbn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Isbn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            
            <label for="Categorie" class="control-label col-md-2">Categorie</label>
            <div class="col-md-10">
               @Html.DropDownList("Categorie", null, "--selecteer categorie--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Beschikbaar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Beschikbaar)
                    @Html.ValidationMessageFor(model => model.Beschikbaar, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Maak" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar lijst van boeken", "Index")
</div>

Project_Krekelhof/Views/Boek/CreateUitlening.cshtml
@model Project_Krekelhof.ViewModels.UitleningViewModel

@{
    if (@Model.Id == 0)
    {
        ViewBag.Title = "Creëer Uitlening";
    }
    else
    {
        ViewBag.Title = "Editeer Uitlening";
    }
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EindeUitlening, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EindeUitlening, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EindeUitlening, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">

            <label for="Item" class="control-label col-md-2">Item</label>
            <div class="col-md-10">
                @Html.DropDownList("Item", null, "--selecteer item--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">

            <label for="Leerling" class="control-label col-md-2">Leerling</label>
            <div class="col-md-10">
                @Html.DropDownList("Leerling", null, "--selecteer leerling--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NaamLeerling, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project_Krekelhof/Views/Boek/Delete.cshtml
@model Project_Krekelhof.ViewModels.BoekViewModel

@{
    ViewBag.Title = "Verwijder boek";
}

<h2>@ViewBag.Title</h2>
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-warning">@ViewBag.ErrorMessage</div>
}
<h4>Weet je zeker dat je het boek @Model.Naam wil verwijderen?</h4>

<div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Verwijder" class="btn btn-default" /> |
            @Html.ActionLink("Terug naar lijst van boeken", "Index")
        </div>
    }
</div>

Project_Krekelhof/Views/Boek/Index.cshtml
<link href="~/Content/Leerlingen.css" rel="stylesheet" type="text/css" />


@model Project_Krekelhof.ViewModels.BoekIndexViewModel
@{
    ViewBag.Title = "Boeken";
}

 <h3 style="padding-top:40px; margin-bottom:100px; font-size: 50px;">@ViewBag.Selection</h3>

@using (Html.BeginForm())
{
    <p style="float:left">
        @Html.TextBox("zoekstring")        
        <input type="submit" id="submitknop" value="Zoek" />
    </p>
}


<form method="post" style="float:left">
    <p style="float:left; padding-left:10px; padding-right:5px;">
        Alleen beschikbare boeken
    </p>
    <input type="checkbox" name="beschikbaar" value="beschikbaar">    
    <input type="submit" value="Zoek" />
   
</form>

<p style="float:right">
    @Html.ActionLink("Nieuw boek toevoegen", "Create")
    <img style="height:25px" src="~/Images/Toevoegen.png" />
</p>



<div>
    @Html.Partial("BoekenLijst", Model)
</div>

@Scripts.Render("~/Scripts/checkbox.js")

Project_Krekelhof/Views/Boek/Uitlenen.cshtml
<link href="~/Content/Leerlingen.css" rel="stylesheet" type="text/css" />

@model Project_Krekelhof.ViewModels.LeerlingIndexViewModel

<div align="center" style="width: 250px; margin: auto; background-color: white;">
    <div>
        @*<table id="table" class="table">
            <tr style="text-align:center;">
                <th>
                    @Html.DisplayNameFor(model => model.Leerlingen.FirstOrDefault().Familienaam)
                </th>
            </tr>
            @foreach (var item in Model.Leerlingen)
            {
                <tr id="tabelrijen">
                    <td>
                        @Html.DisplayFor(modelItem => item.Voornaam)
                        @Html.DisplayFor(modelItem => item.Familienaam)
                    </td>
                </tr>
            }
        </table>*@
        <select size="10">
            @foreach (var item in Model.Leerlingen)
            {
                <option>@Html.DisplayFor(modelItem => item.Voornaam) @Html.DisplayFor(modelItem => item.Familienaam)</option>
            }
        </select>
        
    </div>

    <div>
        @using (Html.BeginForm("UitleningT", "Boek", FormMethod.Post))
        {
            <div class="row">
                &nbsp;
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <button type="button" class="button_example"
                            data-dismiss="modal">
                        Ok
                    </button>
                </div>
            </div>
        }
        @*<script type="text/javascript">
    $(function () {
        $('#approve-btn').click(function () {
            $('#modal-container').modal('hide');
        });
    });
        </script>*@

    </div>

</div> 