Project_Krekelhof/Models/Domain/Leerling.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;

namespace Project_Krekelhof.Models.Domain
{
    public class Leerling
    {
        public int Id { get; set; }
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
        public string Straat { get; set; }
        public int Huisnummer { get; set; }
        //public string Gemeente { get; set; }
        //public int Postcode { get; set; }
        //public string StamBoekNummer { get; set; }

        public string Email { get; set; }
        public string Klas { get; set; }
        public virtual ICollection<Uitlening> Uitleningen { get; set; }

        public Leerling()
        {
            Uitleningen = new HashSet<Uitlening>();
        }

        public Leerling(int id, string voornaam, string familienaam, string straat, int huisnummer, string email, string klas) 
            : this()
        {
            this.Id = id;
            this.Voornaam = voornaam;
            this.Familienaam = familienaam;
            this.Straat = straat;
            this.Huisnummer = huisnummer;
            this.Email = email;
            this.Klas = klas;
        }

        public Leerling(string voornaam, string familienaam, string straat, int huisnummer, string email, string klas)
        {
            this.Voornaam = voornaam;
            this.Familienaam = familienaam;
            this.Straat = straat;
            this.Huisnummer = huisnummer;
            this.Email = email;
            this.Klas = klas;
        }

        public void KrijgLening(Uitlening uitlening)
        {
            if (Uitleningen.Count >= 3)
            {
                throw new ApplicationException("Lener mag maar 3 uitleningen hebben!");
            }

            Uitleningen.Add(uitlening);

        }

        public void CheckLeningUit(Uitlening uitlening)
        {
            Uitleningen.Remove(uitlening);
        }

        public override string ToString()
        {
            return Voornaam + " " + Familienaam;
        }
    }
}

Project_Krekelhof/ViewModels/LeerlingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Project_Krekelhof.Models.Domain;

namespace Project_Krekelhof.ViewModels
{
    public class LeerlingViewModel
    {
        public int Id { get; set; }
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
        public string Straat { get; set; }
        public int Huisnummer { get; set; }
        public string Email { get; set; }
        public string Klas { get; set; }


        public LeerlingViewModel()
        {
        }
        public LeerlingViewModel(Leerling l)
        {
            Id = l.Id;
            Voornaam = l.Voornaam;
            Familienaam = l.Familienaam;
            Straat = l.Straat;
            Huisnummer = l.Huisnummer;
            Email = l.Email;
            Klas = l.Klas;
        }
    }

    public class LeerlingIndexViewModel
    {
        public IEnumerable<LeerlingViewModel> Leerlingen { get; set; }

        public LeerlingIndexViewModel(IEnumerable<Leerling> leerlingen)
        {
            Leerlingen = leerlingen.Select(s => new LeerlingViewModel()
            {
                Id = s.Id,
                Voornaam = s.Voornaam,
                Familienaam = s.Familienaam,
                Straat = s.Straat,
                Huisnummer = s.Huisnummer,
                Email = s.Email,
                Klas = s.Klas
            });
        }    
    }
}

Project_Krekelhof/Controllers/LeerlingController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using MySql.Data.MySqlClient;
using Project_Krekelhof.Models.DAL;
using Project_Krekelhof.Models.Domain;
using Project_Krekelhof.ViewModels;

namespace Project_Krekelhof.Controllers
{
    public class LeerlingController : Controller
    {
        private ILeerlingRepository leerlingRepository;
        //private IUitleningRepository UitleningRepository;

        private Medewerker medewerker;
        private Gebruiker gebruiker;

        public LeerlingController(ILeerlingRepository leerlingRepository)
        {
            gebruiker = new Gebruiker(null, null, null, null, null, leerlingRepository, null);
            medewerker = new Medewerker(null, null, null, null, null, leerlingRepository, null);
            this.leerlingRepository = leerlingRepository;
        }

        [HttpGet]
        public ActionResult Index(String zoekstring = null)
        {
            IEnumerable<Leerling> leerlingen;
            if (!String.IsNullOrEmpty(zoekstring))
            {
                leerlingen = gebruiker.GeefLeerlingen(zoekstring);
                ViewBag.Selection = "Alle leerlingen met '" + zoekstring + "'";
            }
            else
            {
                leerlingen = gebruiker.GeefLeerlingen(zoekstring);
                ViewBag.Selection = "Alle leerlingen";
            }
            if (Request.IsAjaxRequest())
                return PartialView("Lijst", new LeerlingIndexViewModel(leerlingen));

            return View(new LeerlingIndexViewModel(leerlingen));
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            DataSet ds = new DataSet();
            if (Request.Files["file"].ContentLength > 0)
            {
                string fileExtension =
                    System.IO.Path.GetExtension(Request.Files["file"].FileName);

                if (fileExtension == ".xls" || fileExtension == ".xlsx")
                {
                    string fileLocation = Server.MapPath("~/Content/") + Request.Files["file"].FileName;
                    if (System.IO.File.Exists(fileLocation))
                    {

                        System.IO.File.Delete(fileLocation);
                    }
                    Request.Files["file"].SaveAs(fileLocation);
                    string excelConnectionString = string.Empty;
                    excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" +
                    fileLocation + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                    //connection String for xls file format.
                    if (fileExtension == ".xls")
                    {
                        excelConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" +
                        fileLocation + ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";
                    }
                    //connection String for xlsx file format.
                    else if (fileExtension == ".xlsx")
                    {
                        excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" +
                        fileLocation + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                    }
                    //Create Connection to Excel work book and add oledb namespace
                    OleDbConnection excelConnection = new OleDbConnection(excelConnectionString);
                    excelConnection.Open();
                    DataTable dt = new DataTable();

                    dt = excelConnection.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                    if (dt == null)
                    {
                        return null;
                    }

                    String[] excelSheets = new String[dt.Rows.Count];
                    int t = 0;
                    //excel data saves in temp file here.
                    foreach (DataRow row in dt.Rows)
                    {
                        excelSheets[t] = row["TABLE_NAME"].ToString();
                        t++;
                    }
                    OleDbConnection excelConnection1 = new OleDbConnection(excelConnectionString);

                    string query = string.Format("Select * from [{0}]", excelSheets[0]);
                    using (OleDbDataAdapter dataAdapter = new OleDbDataAdapter(query, excelConnection1))
                    {
                        dataAdapter.Fill(ds);
                    }
                }
                if (fileExtension.ToString().ToLower().Equals(".xml"))
                {
                    string fileLocation = Server.MapPath("~/Content/") + Request.Files["FileUpload"].FileName;
                    if (System.IO.File.Exists(fileLocation))
                    {
                        System.IO.File.Delete(fileLocation);
                    }

                    Request.Files["FileUpload"].SaveAs(fileLocation);
                    XmlTextReader xmlreader = new XmlTextReader(fileLocation);
                    // DataSet ds = new DataSet();
                    ds.ReadXml(xmlreader);
                    xmlreader.Close();
                }

                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    string connection = ConfigurationManager.ConnectionStrings["Krekelschool"].ConnectionString;
                    MySqlConnection connect = new MySqlConnection(connection);
                    string query =
                        "INSERT INTO Leerlingen(Voornaam,Familienaam,Straat,HuisNummer,Email,Klas) " +
                        "Values(@VOORNAAM, @FAMILIENAAM, @STRAAT, @HUISNUMMER, @EMAIL, @KLAS)";

                    connect.Open();
                    MySqlCommand command = new MySqlCommand(query, connect);
                    command.Parameters.AddWithValue("@VOORNAAM", ds.Tables[0].Rows[i][0].ToString());
                    command.Parameters.AddWithValue("@FAMILIENAAM", ds.Tables[0].Rows[i][1].ToString());
                    command.Parameters.AddWithValue("@STRAAT", ds.Tables[0].Rows[i][2].ToString());
                    command.Parameters.AddWithValue("@HUISNUMMER", ds.Tables[0].Rows[i][3].ToString());
                    command.Parameters.AddWithValue("@EMAIL", ds.Tables[0].Rows[i][4].ToString());
                    command.Parameters.AddWithValue("@KLAS", ds.Tables[0].Rows[i][5].ToString());
                    command.ExecuteNonQuery();
                    connect.Close();
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            Leerling leerling = new Leerling();
            ViewBag.Title = "Leerling toevoegen";
            return View(new LeerlingViewModel(leerling));
        }

        [HttpPost]
        public ActionResult Create(LeerlingViewModel lvm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Leerling leerling = new Leerling();
                    MapToLeerling(lvm, leerling);
                    leerlingRepository.Add(leerling);
                    leerlingRepository.SaveChanges();
                    TempData["Message"] = String.Format("{0} werd gecreëerd.", leerling.Voornaam);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(lvm);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Leerling leerling = leerlingRepository.FindById(id);
            if (leerling == null)
                return HttpNotFound();
            return View("Create", new LeerlingViewModel(leerling));
        }

        [HttpPost]
        public ActionResult Edit(int id, LeerlingViewModel lvm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Leerling leerling = leerlingRepository.FindById(id);
                    MapToLeerling(lvm, leerling);
                    leerlingRepository .SaveChanges();
                    TempData["message"] = String.Format("Leerling {0} werd aangepast", leerling.Voornaam);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View("Create", lvm);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Leerling leerling = leerlingRepository.FindById(id);
            if (leerling == null)
                return HttpNotFound();
            return View(new LeerlingViewModel(leerling));
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Leerling leerling = leerlingRepository.FindById(id);
                if (leerling == null)
                    return HttpNotFound();
                leerlingRepository.Delete(leerling);
                leerlingRepository.SaveChanges();
                TempData["message"] = String.Format("Leerling {0} werd verwijderd", leerling.Voornaam);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Verwijderen Leerling mislukt. Probeer opnieuw. ";
            }
            return RedirectToAction("Index");
        }

        private void MapToLeerling(LeerlingViewModel lvm, Leerling leerling)
        {
            //leerling.Id = lvm.Id;
            leerling.Voornaam = lvm.Voornaam;
            leerling.Familienaam = lvm.Familienaam;

Project_Krekelhof/Views/Leerling/Create.cshtml
@model Project_Krekelhof.ViewModels.LeerlingViewModel

@{
    if (@Model.Id == 0)
    {
        ViewBag.Title = "Creëer cd";
    }
    else
    {
        ViewBag.Title = "Editeer Cd";
    }
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Voornaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Voornaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Voornaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Familienaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Familienaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Familienaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Straat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Straat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Straat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Huisnummer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Huisnummer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Huisnummer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Klas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Klas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Klas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Maak" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar lijst van leerlingen", "Index")
</div>

Project_Krekelhof/Views/Leerling/Delete.cshtml
@model Project_Krekelhof.ViewModels.LeerlingViewModel

@{
    ViewBag.Title = "Verwijder Leerling";
}

<h2>@ViewBag.Title</h2>
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-warning">@ViewBag.ErrorMessage</div>
}
<h4>Weet je zeker dat je de Leerling @Model.Voornaam @Model.Familienaam wil verwijderen?</h4>

<div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Verwijder" class="btn btn-default" /> |
            @Html.ActionLink("Terug naar lijst van leerlingen", "Index")
        </div>
    }
</div>

Project_Krekelhof/Views/Leerling/Index.cshtml
<link href="~/Content/Leerlingen.css" rel="stylesheet" type="text/css" />


@model Project_Krekelhof.ViewModels.LeerlingIndexViewModel
@{
    ViewBag.Title = "Leerlingen";
}

<h3 style="padding-top:40px; margin-bottom:100px; font-size: 50px;">@ViewBag.Selection</h3>

@using (Html.BeginForm("Index", "Leerling", FormMethod.Get))
{
    <p style="float:left">
        @Html.TextBox("zoekstring")
        <input type="submit" id="submitknop" value="Zoek" />
    </p>
}

<p style="float:right">
    @Html.ActionLink("Nieuwe leerling toevoegen", "Create")
    <img style="height:25px" src="~/Images/Toevoegen.png" />
</p>

@using (Html.BeginForm("Index", "Leerling", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" />
    <input type="submit" value="OK" />
}  


<div>
    @Html.Partial("LeerlingenLijst", Model)
</div>

Project_Krekelhof/Views/Leerling/Index_Kasper.cshtml
<link href="~/Content/Leerlingen.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Leerlingen";
}
<body>
    <h2>Leerlingen</h2>
    <p>Leerlingen (2)</p>

    <div id="leerlingen">
        <button ><img src="~/Images/Toevoegen.png" />Leerling toevoegen</button>
        <button ><img src="~/Images/Bewerken.png" />Leerling bewerken</button>
        <button ><img src="~/Images/Vinkje.png" />Leerling verwijderen</button>
    
        
    </div>

    <div id="zoekform">

        <form action="index.html" method="post">

            <h1 id="h1zoeken"><img src="~/Images/Lupe.png" /> Zoeken</h1>

            <fieldset>
                <input type="text" id="name" name="user_name">
            </fieldset>

            <fieldset id="Lijst">
                <label for="zoek">Op:</label>
                <select id="zoek" name="zoek">
                    <optgroup label="Leerling">
                        <option value="Voornaam">Voornaam</option>
                        <option value="Voornaam">Famielienaam</option>
                        

                    </optgroup>
                </select>

            </fieldset>
            <button id="knop" type="button" onclick="location.href = '/../Uitlening/Index'">Zoek</button>
        </form>

    </div>


    <div id="Scroll">

        <table class="tg" style="undefined;table-layout: fixed; width: 100%">
            <colgroup>
                <col style="width: 33px">
            </colgroup>
            <thead>
                <tr>
                    <th class="tg-031e">Nr.</th>
                    <th class="tg-031e">Lening</th>                    
                    <th class="tg-031e">Voornaam</th>
                    <th class="tg-031e">Familienaam</th>
                    <th class="tg-031e">Klas</th>
                    <th style="width: 500px"class="tg-031e">Adres</th>
                    <th class="tg-031e">Telefoonnummer</th>
                    


                </tr>
            </thead>
            <tbody id="Scroll">
                <tr>
                    <td class="tg-031e">1</td>
                    <td class="tg-031e">Ja</td>
                    <td class="tg-031e">Kasper</td>
                    <td class="tg-031e">Ottoy</td>
                    <td class="tg-031e">2 TIN A</td>
                    <td class="tg-031e">Steenweg op aalst 37, 9308 Hofstade</td>
                    <td class="tg-031e">0478/83.66.19</td>
                </tr>
                <tr>
                    <td class="tg-031e">2</td>
                    <td class="tg-031e">Ja</td>
                    <td class="tg-031e">Ben</td>
                    <td class="tg-031e">Goossens</td>
                    <td class="tg-031e">2 TIN A</td>
                    <td class="tg-031e">Vlekkemdorp 23, 9420 Erpe-Mere</td>
                    <td class="tg-031e">-</td>
                </tr>
                <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                </tr>
                <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                </tr>
                <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                </tr>
                <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                </tr>

                <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                </tr>

                <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                </tr>

                <tr>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                    <td class="tg-031e"></td>
                </tr>

            </tbody>

        </table>

    </div>

    <div id="ganaardiv">
        <button id="ganaar" disabled>Bekijk geschiedenis uitlening</button>
    </div>




</body>

Project_Krekelhof/Views/Leerling/LeerlingenLijst.cshtml
<link href="~/Content/Leerlingen.css" rel="stylesheet" type="text/css" />

@model Project_Krekelhof.ViewModels.LeerlingIndexViewModel



<table class="table">
    <tr style="text-align:center;">
        <th>
            @Html.DisplayNameFor(model => model.Leerlingen.FirstOrDefault().Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Leerlingen.FirstOrDefault().Voornaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Leerlingen.FirstOrDefault().Familienaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Leerlingen.FirstOrDefault().Straat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Leerlingen.FirstOrDefault().Huisnummer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Leerlingen.FirstOrDefault().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Leerlingen.FirstOrDefault().Klas)
        </th>
        <th></th>
    </tr>

        @foreach (var item in Model.Leerlingen)
        {
                <tr id="tabelrijen">
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Voornaam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Familienaam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Straat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Huisnummer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Klas)
                    </td>
                    <td>

                        <a>
                            <img src="~/Images/Bewerken.png" style="width:10px; height:10px;" />
                            @Html.ActionLink("Aanpassen", "Edit", new { id = item.Id }) |

                        </a>
                        @Html.ActionLink("Verijderen", "Delete", new { id = item.Id, @class = "Deleteknop" })
                    </td>
                </tr>

        }

</table>